import { Injectable } from '@angular/core';
import { ShiftDTO } from '../../shared/models/DTOs/Incoming/ShiftDTO';
import { ScheduleEntryDTO } from '../../shared/models/DTOs/Incoming/ScheduleEntryDTO';
import { Entity } from '../../shared/models/database/entity';
import { EntityWorkerMemberDTO } from '../../shared/models/DTOs/Incoming/EntityWorkerMemberDTO';

@Injectable({
  providedIn: 'root'
})
export class ScheduleAuxService {

  constructor() { }

  public createNewScheduleEntry(date: Date, shift: ShiftDTO) : ScheduleEntryDTO{

    // Set the start date and end date based on the selected shift
    let startDate = new Date(date.getTime());
    // Extract hours and minutes from the shift start hour
    // Note: The shiftStartHour is expected to be in the format "HH:mm".
    const [hours, minutes] = shift?.shiftStartHour.toString().split(':').map(Number) || [0, 0];
    startDate.setHours(hours, minutes, 0, 0);

    let endDate = new Date(startDate.getTime());
    // Extract hours and minutes from the shift duration
    // Note: The shiftDuration is expected to be in the format "HH:mm".
    const [durationHours, durationMinutes] = shift?.shiftDuration.toString().split(':').map(Number) || [0, 0];
    endDate.setHours(endDate.getHours() + (durationHours));
    endDate.setMinutes(endDate.getMinutes() + (durationMinutes));

    // Create a new schedule entry with the selected shift and calculated start and end dates
    // Note: The scheduleEntryId is set to an empty string as it will be generated by the backend.
    let newScheduleEntry = new ScheduleEntryDTO("", shift.shiftId, startDate, endDate, shift, []);

    return newScheduleEntry;
  }

  public async applyRotationCycleToWorker(worker: EntityWorkerMemberDTO,
    scheduleEntries: ScheduleEntryDTO[], 
    cycleStartDate: Date, 
    cycleEndDate: Date): Promise<ScheduleEntryDTO[]> {

      let updatedEntries = [...scheduleEntries];



      return updatedEntries;
  }
}
