#!/usr/bin/env python3
"""
Script to add French translations to XLIFF file
"""

import re
import xml.etree.ElementTree as ET
from typing import Dict

# French translations dictionary
TRANSLATIONS: Dict[str, str] = {
    # Common UI terms
    "Members": "Membres",
    "Rules": "Règles",
    "Shifts": "Équipes",
    "Skill Assignments:": "Affectations de compétences :",
    "Absence Type": "Type d'absence",
    "Observations": "Observations",
    "Start Date": "Date de début",
    "End Date": "Date de fin",
    "Status": "Statut",
    "Pending": "En attente",
    "Absence Start Date": "Date de début d'absence",
    "Absence End Date": "Date de fin d'absence",
    "Save": "Enregistrer",
    "Create": "Créer",
    "Actions": "Actions",
    "Absences": "Absences",
    "Add Absence": "Ajouter une absence",
    "Cancel": "Annuler",
    " Full Day Absence ": " Absence toute la journée ",
    "Start Time": "Heure de début",
    "End Time": "Heure de fin",
    "Are you sure you want to delete this entity? All data will be erased and everyone associated with this work entity will no longer have access.": "Êtes-vous sûr de vouloir supprimer cette entité ? Toutes les données seront effacées et toutes les personnes associées à cette entité de travail n'y auront plus accès.",
    "Delete": "Supprimer",
    "Edit": "Modifier",
    "Name": "Nom",
    "Type": "Type",
    "Description": "Description",
    "Email": "E-mail",
    "Phone": "Téléphone",
    "Address": "Adresse",
    "City": "Ville",
    "Country": "Pays",
    "Postal Code": "Code postal",
    "Business": "Entreprise",
    "Department": "Département",
    "Other": "Autre",
    "Add": "Ajouter",
    "Remove": "Retirer",
    "Close": "Fermer",
    "Submit": "Soumettre",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Export": "Exporter",
    "Import": "Importer",
    "Print": "Imprimer",
    "Download": "Télécharger",
    "Upload": "Téléverser",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Finish": "Terminer",
    "Yes": "Oui",
    "No": "Non",
    "OK": "OK",
    "Apply": "Appliquer",
    "Reset": "Réinitialiser",
    "Clear": "Effacer",
    "Refresh": "Actualiser",
    "Update": "Mettre à jour",
    "View": "Voir",
    "Details": "Détails",
    "Settings": "Paramètres",
    "Help": "Aide",
    "About": "À propos",
    "Contact": "Contact",
    "Privacy": "Confidentialité",
    "Terms": "Conditions",
    "Login": "Connexion",
    "Logout": "Déconnexion",
    "Register": "S'inscrire",
    "Sign Up": "S'inscrire",
    "Sign In": "Se connecter",
    "Forgot Password": "Mot de passe oublié",
    "Password": "Mot de passe",
    "Username": "Nom d'utilisateur",
    "Confirm Password": "Confirmer le mot de passe",
    "New Password": "Nouveau mot de passe",
    "Old Password": "Ancien mot de passe",
    "Current Password": "Mot de passe actuel",
    "Profile": "Profil",
    "Dashboard": "Tableau de bord",
    "Home": "Accueil",
    "Welcome": "Bienvenue",
    "Account": "Compte",
    "My Account": "Mon compte",
    "User": "Utilisateur",
    "Users": "Utilisateurs",
    "Admin": "Administrateur",
    "Administrator": "Administrateur",
    "Role": "Rôle",
    "Roles": "Rôles",
    "Permission": "Permission",
    "Permissions": "Permissions",
    "Group": "Groupe",
    "Groups": "Groupes",
    "Team": "Équipe",
    "Teams": "Équipes",
    "Organization": "Organisation",
    "Organizations": "Organisations",
    "Entity": "Entité",
    "Entities": "Entités",
    "Worker": "Travailleur",
    "Workers": "Travailleurs",
    "Employee": "Employé",
    "Employees": "Employés",
    "Manager": "Gestionnaire",
    "Managers": "Gestionnaires",
    "Schedule": "Horaire",
    "Schedules": "Horaires",
    "Shift": "Équipe",
    "Rotation": "Rotation",
    "Rotations": "Rotations",
    "Break": "Pause",
    "Breaks": "Pauses",
    "Holiday": "Jour férié",
    "Holidays": "Jours fériés",
    "Vacation": "Vacances",
    "Vacations": "Vacances",
    "Leave": "Congé",
    "Sick Leave": "Congé maladie",
    "Personal Leave": "Congé personnel",
    "Maternity Leave": "Congé maternité",
    "Paternity Leave": "Congé paternité",
    "Unpaid Leave": "Congé sans solde",
    "Paid Leave": "Congé payé",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "Cancelled": "Annulé",
    "Active": "Actif",
    "Inactive": "Inactif",
    "Enabled": "Activé",
    "Disabled": "Désactivé",
    "Available": "Disponible",
    "Unavailable": "Indisponible",
    "Online": "En ligne",
    "Offline": "Hors ligne",
    "Success": "Succès",
    "Error": "Erreur",
    "Warning": "Avertissement",
    "Info": "Info",
    "Information": "Information",
    "Message": "Message",
    "Messages": "Messages",
    "Notification": "Notification",
    "Notifications": "Notifications",
    "Alert": "Alerte",
    "Alerts": "Alertes",
    "Reminder": "Rappel",
    "Reminders": "Rappels",
    "Calendar": "Calendrier",
    "Date": "Date",
    "Time": "Heure",
    "DateTime": "Date et heure",
    "Day": "Jour",
    "Days": "Jours",
    "Week": "Semaine",
    "Weeks": "Semaines",
    "Month": "Mois",
    "Months": "Mois",
    "Year": "Année",
    "Years": "Années",
    "Hour": "Heure",
    "Hours": "Heures",
    "Minute": "Minute",
    "Minutes": "Minutes",
    "Second": "Seconde",
    "Seconds": "Secondes",
    "Monday": "Lundi",
    "Tuesday": "Mardi",
    "Wednesday": "Mercredi",
    "Thursday": "Jeudi",
    "Friday": "Vendredi",
    "Saturday": "Samedi",
    "Sunday": "Dimanche",
    "January": "Janvier",
    "February": "Février",
    "March": "Mars",
    "April": "Avril",
    "May": "Mai",
    "June": "Juin",
    "July": "Juillet",
    "August": "Août",
    "September": "Septembre",
    "October": "Octobre",
    "November": "Novembre",
    "December": "Décembre",
    "Today": "Aujourd'hui",
    "Yesterday": "Hier",
    "Tomorrow": "Demain",
    "This Week": "Cette semaine",
    "Last Week": "Semaine dernière",
    "Next Week": "Semaine prochaine",
    "This Month": "Ce mois-ci",
    "Last Month": "Mois dernier",
    "Next Month": "Mois prochain",
    "This Year": "Cette année",
    "Last Year": "Année dernière",
    "Next Year": "Année prochaine",
    "Duration": "Durée",
    "From": "De",
    "To": "À",
    "Between": "Entre",
    "All": "Tous",
    "None": "Aucun",
    "Select": "Sélectionner",
    "Selected": "Sélectionné",
    "Deselect": "Désélectionner",
    "Select All": "Tout sélectionner",
    "Deselect All": "Tout désélectionner",
    "Show": "Afficher",
    "Hide": "Masquer",
    "Expand": "Développer",
    "Collapse": "Réduire",
    "More": "Plus",
    "Less": "Moins",
    "Loading": "Chargement",
    "Loading...": "Chargement...",
    "Please wait...": "Veuillez patienter...",
    "Processing": "Traitement en cours",
    "Saving": "Enregistrement",
    "Saved": "Enregistré",
    "Sending": "Envoi",
    "Sent": "Envoyé",
    "Deleting": "Suppression",
    "Deleted": "Supprimé",
    "Creating": "Création",
    "Created": "Créé",
    "Updating": "Mise à jour",
    "Updated": "Mis à jour",
    "Required": "Obligatoire",
    "Optional": "Facultatif",
    "Invalid": "Invalide",
    "Valid": "Valide",
    "Empty": "Vide",
    "Full": "Plein",
    "Total": "Total",
    "Count": "Nombre",
    "Sum": "Somme",
    "Average": "Moyenne",
    "Min": "Min",
    "Max": "Max",
    "First": "Premier",
    "Last": "Dernier",
    "New": "Nouveau",
    "Old": "Ancien",
    "Recent": "Récent",
    "Latest": "Dernier",
    "Oldest": "Plus ancien",
    "Sort": "Trier",
    "Sorted": "Trié",
    "Ascending": "Croissant",
    "Descending": "Décroissant",
    "Page": "Page",
    "Pages": "Pages",
    "of": "de",
    "per page": "par page",
    "Items per page": "Éléments par page",
    "Go to page": "Aller à la page",
    "First page": "Première page",
    "Last page": "Dernière page",
    "Next page": "Page suivante",
    "Previous page": "Page précédente",
    "No data": "Aucune donnée",
    "No results": "Aucun résultat",
    "No items": "Aucun élément",
    "No records": "Aucun enregistrement",
    "Not found": "Introuvable",
    "File": "Fichier",
    "Files": "Fichiers",
    "Folder": "Dossier",
    "Folders": "Dossiers",
    "Document": "Document",
    "Documents": "Documents",
    "Image": "Image",
    "Images": "Images",
    "Video": "Vidéo",
    "Videos": "Vidéos",
    "Audio": "Audio",
    "Size": "Taille",
    "Format": "Format",
    "Extension": "Extension",
    "Version": "Version",
    "Language": "Langue",
    "Languages": "Langues",
    "English": "Anglais",
    "French": "Français",
    "Spanish": "Espagnol",
    "German": "Allemand",
    "Italian": "Italien",
    "Portuguese": "Portugais",
    "Chinese": "Chinois",
    "Japanese": "Japonais",
    "Korean": "Coréen",
    "Arabic": "Arabe",
    "Russian": "Russe",
    "Timezone": "Fuseau horaire",
    "Theme": "Thème",
    "Light": "Clair",
    "Dark": "Sombre",
    "Auto": "Auto",
    "Color": "Couleur",
    "Colors": "Couleurs",
    "Font": "Police",
    "Fonts": "Polices",
    "Size": "Taille",
    "Small": "Petit",
    "Medium": "Moyen",
    "Large": "Grand",
    "Extra Small": "Très petit",
    "Extra Large": "Très grand",
    "Width": "Largeur",
    "Height": "Hauteur",
    "Position": "Position",
    "Top": "Haut",
    "Bottom": "Bas",
    "Left": "Gauche",
    "Right": "Droite",
    "Center": "Centre",
    "Start": "Début",
    "End": "Fin",
    "Open": "Ouvrir",
    "Opened": "Ouvert",
    "Closed": "Fermé",
    "Visible": "Visible",
    "Hidden": "Masqué",
    "Public": "Public",
    "Private": "Privé",
    "Shared": "Partagé",
    "Personal": "Personnel",
    "General": "Général",
    "Specific": "Spécifique",
    "Custom": "Personnalisé",
    "Default": "Par défaut",
    "Standard": "Standard",
    "Advanced": "Avancé",
    "Basic": "Basique",
    "Simple": "Simple",
    "Complex": "Complexe",
    "Easy": "Facile",
    "Hard": "Difficile",
    "Low": "Bas",
    "Medium": "Moyen",
    "High": "Élevé",
    "Priority": "Priorité",
    "Urgent": "Urgent",
    "Important": "Important",
    "Normal": "Normal",
    "Critical": "Critique",
    "Major": "Majeur",
    "Minor": "Mineur",
    "Trivial": "Trivial",
    "Blocker": "Bloquant",
    "Feature": "Fonctionnalité",
    "Features": "Fonctionnalités",
    "Bug": "Bogue",
    "Bugs": "Bogues",
    "Issue": "Problème",
    "Issues": "Problèmes",
    "Task": "Tâche",
    "Tasks": "Tâches",
    "Project": "Projet",
    "Projects": "Projets",
    "Category": "Catégorie",
    "Categories": "Catégories",
    "Tag": "Étiquette",
    "Tags": "Étiquettes",
    "Label": "Libellé",
    "Labels": "Libellés",
    "Note": "Note",
    "Notes": "Notes",
    "Comment": "Commentaire",
    "Comments": "Commentaires",
    "Reply": "Répondre",
    "Replies": "Réponses",
    "Attachment": "Pièce jointe",
    "Attachments": "Pièces jointes",
    "Link": "Lien",
    "Links": "Liens",
    "URL": "URL",
    "Share": "Partager",
    "Copy": "Copier",
    "Paste": "Coller",
    "Cut": "Couper",
    "Duplicate": "Dupliquer",
    "Move": "Déplacer",
    "Rename": "Renommer",
    "Archive": "Archiver",
    "Unarchive": "Désarchiver",
    "Restore": "Restaurer",
    "Undo": "Annuler",
    "Redo": "Rétablir",
    "Preview": "Aperçu",
    "Full Screen": "Plein écran",
    "Exit Full Screen": "Quitter le plein écran",
    "Zoom In": "Agrandir",
    "Zoom Out": "Réduire",
    "Fit": "Ajuster",
    "Actual Size": "Taille réelle",
    "Rotate": "Pivoter",
    "Flip": "Retourner",
    "Crop": "Recadrer",
    "Resize": "Redimensionner",
    "Adjust": "Ajuster",
    "Brightness": "Luminosité",
    "Contrast": "Contraste",
    "Saturation": "Saturation",
    "Opacity": "Opacité",
    "Quality": "Qualité",
    "Resolution": "Résolution",
    "Compress": "Compresser",
    "Decompress": "Décompresser",
    "Encrypt": "Chiffrer",
    "Decrypt": "Déchiffrer",
    "Lock": "Verrouiller",
    "Unlock": "Déverrouiller",
    "Pin": "Épingler",
    "Unpin": "Désépingler",
    "Bookmark": "Marque-page",
    "Favorite": "Favori",
    "Favorites": "Favoris",
    "Star": "Étoile",
    "Like": "J'aime",
    "Dislike": "Je n'aime pas",
    "Follow": "Suivre",
    "Unfollow": "Ne plus suivre",
    "Subscribe": "S'abonner",
    "Unsubscribe": "Se désabonner",
    "Block": "Bloquer",
    "Unblock": "Débloquer",
    "Report": "Signaler",
    "Flag": "Signaler",
    "Spam": "Spam",
    "Abuse": "Abus",
    "Violation": "Violation",
    "Copyright": "Droit d'auteur",
    "License": "Licence",
    "Legal": "Légal",
    "Terms of Service": "Conditions d'utilisation",
    "Privacy Policy": "Politique de confidentialité",
    "Cookie Policy": "Politique relative aux cookies",
    "Cookies": "Cookies",
    "Analytics": "Analytiques",
    "Statistics": "Statistiques",
    "Stats": "Stats",
    "Chart": "Graphique",
    "Charts": "Graphiques",
    "Graph": "Graphique",
    "Graphs": "Graphiques",
    "Table": "Tableau",
    "Tables": "Tableaux",
    "List": "Liste",
    "Lists": "Listes",
    "Grid": "Grille",
    "Grids": "Grilles",
    "Timeline": "Chronologie",
    "Map": "Carte",
    "Maps": "Cartes",
    "Location": "Emplacement",
    "Locations": "Emplacements",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Coordinates": "Coordonnées",
    "Distance": "Distance",
    "Direction": "Direction",
    "North": "Nord",
    "South": "Sud",
    "East": "Est",
    "West": "Ouest",
    "True": "Vrai",
    "False": "Faux",
    "On": "Activé",
    "Off": "Désactivé",
    "Enabled": "Activé",
    "Disabled": "Désactivé",
    "Allowed": "Autorisé",
    "Denied": "Refusé",
    "Granted": "Accordé",
    "Revoked": "Révoqué",
    "Accepted": "Accepté",
    "Declined": "Refusé",
    "Confirmed": "Confirmé",
    "Unconfirmed": "Non confirmé",
    "Verified": "Vérifié",
    "Unverified": "Non vérifié",
    "Complete": "Terminé",
    "Incomplete": "Incomplet",
    "Completed": "Terminé",
    "In Progress": "En cours",
    "Not Started": "Non commencé",
    "On Hold": "En attente",
    "Paused": "En pause",
    "Stopped": "Arrêté",
    "Running": "En cours",
    "Finished": "Terminé",
    "Failed": "Échoué",
    "Passed": "Réussi",
    "Skipped": "Ignoré",
    "Ignored": "Ignoré",
    "Archived": "Archivé",
    "Draft": "Brouillon",
    "Published": "Publié",
    "Unpublished": "Non publié",
    "Scheduled": "Planifié",
    "Expired": "Expiré",
    "Valid Until": "Valide jusqu'au",
    "Expires On": "Expire le",
    "Created": "Créé",
    "Created By": "Créé par",
    "Created At": "Créé le",
    "Modified": "Modifié",
    "Modified By": "Modifié par",
    "Modified At": "Modifié le",
    "Updated At": "Mis à jour le",
    "Updated By": "Mis à jour par",
    "Deleted At": "Supprimé le",
    "Deleted By": "Supprimé par",
    "Last Modified": "Dernière modification",
    "Last Updated": "Dernière mise à jour",
    "Last Login": "Dernière connexion",
    "Last Seen": "Vu pour la dernière fois",
    "Member Since": "Membre depuis",
    "Joined": "Inscrit",
    "Joined At": "Inscrit le",
    "Left": "Quitté",
    "Left At": "Quitté le",
    "Owner": "Propriétaire",
    "Owned By": "Propriété de",
    "Assigned To": "Attribué à",
    "Assigned By": "Attribué par",
    "Reviewer": "Réviseur",
    "Reviewed By": "Révisé par",
    "Approver": "Approbateur",
    "Approved By": "Approuvé par",
    "Requested By": "Demandé par",
    "Submitted By": "Soumis par",
    "Author": "Auteur",
    "Editor": "Éditeur",
    "Contributor": "Contributeur",
    "Viewer": "Observateur",
    "Guest": "Invité",
    "Anonymous": "Anonyme",
    "System": "Système",
    "Automatic": "Automatique",
    "Manual": "Manuel",
    "Read Only": "Lecture seule",
    "Read/Write": "Lecture/Écriture",
    "Full Access": "Accès complet",
    "No Access": "Aucun accès",
    "Limited Access": "Accès limité",
    "View Only": "Affichage uniquement",
    "Edit Only": "Modification uniquement",
    "Can View": "Peut voir",
    "Can Edit": "Peut modifier",
    "Can Delete": "Peut supprimer",
    "Can Create": "Peut créer",
    "Can Share": "Peut partager",
    "Can Download": "Peut télécharger",
    "Can Upload": "Peut téléverser",
    "Can Comment": "Peut commenter",
    "Can Approve": "Peut approuver",
    "Can Reject": "Peut rejeter",
    "Skill": "Compétence",
    "Skills": "Compétences",
    "Required Skills": "Compétences requises",
    "Optional Skills": "Compétences facultatives",
    "Qualification": "Qualification",
    "Qualifications": "Qualifications",
    "Certificate": "Certificat",
    "Certificates": "Certificats",
    "Training": "Formation",
    "Experience": "Expérience",
    "Level": "Niveau",
    "Beginner": "Débutant",
    "Intermediate": "Intermédiaire",
    "Advanced": "Avancé",
    "Expert": "Expert",
    "Master": "Maître",
    "Novice": "Novice",
    "Proficient": "Compétent",
    "Coverage": "Couverture",
    "Capacity": "Capacité",
    "Workload": "Charge de travail",
    "Overtime": "Heures supplémentaires",
    "Undertime": "Heures en moins",
    "Full Time": "Temps plein",
    "Part Time": "Temps partiel",
    "Contract": "Contrat",
    "Temporary": "Temporaire",
    "Permanent": "Permanent",
    "Hourly": "Horaire",
    "Daily": "Quotidien",
    "Weekly": "Hebdomadaire",
    "Monthly": "Mensuel",
    "Yearly": "Annuel",
    "Annual": "Annuel",
    "Quarterly": "Trimestriel",
    "Biweekly": "Bihebdomadaire",
    "Semimonthly": "Bimensuel",
    "Rate": "Taux",
    "Pay Rate": "Taux de rémunération",
    "Salary": "Salaire",
    "Wage": "Salaire",
    "Bonus": "Prime",
    "Commission": "Commission",
    "Allowance": "Allocation",
    "Deduction": "Déduction",
    "Tax": "Taxe",
    "Gross": "Brut",
    "Net": "Net",
    "Before Tax": "Avant impôt",
    "After Tax": "Après impôt",
    "Benefit": "Avantage",
    "Benefits": "Avantages",
    "Insurance": "Assurance",
    "Health": "Santé",
    "Dental": "Dentaire",
    "Vision": "Vision",
    "Retirement": "Retraite",
    "Pension": "Pension",
    "401k": "401k",
    "Stock": "Action",
    "Equity": "Équité",
    "Option": "Option",
    "Options": "Options",
    "Expense": "Dépense",
    "Expenses": "Dépenses",
    "Reimbursement": "Remboursement",
    "Invoice": "Facture",
    "Invoices": "Factures",
    "Receipt": "Reçu",
    "Receipts": "Reçus",
    "Payment": "Paiement",
    "Payments": "Paiements",
    "Transaction": "Transaction",
    "Transactions": "Transactions",
    "Balance": "Solde",
    "Credit": "Crédit",
    "Debit": "Débit",
    "Amount": "Montant",
    "Quantity": "Quantité",
    "Unit": "Unité",
    "Units": "Unités",
    "Price": "Prix",
    "Cost": "Coût",
    "Value": "Valeur",
    "Discount": "Remise",
    "Subtotal": "Sous-total",
    "Tax": "Taxe",
    "Shipping": "Livraison",
    "Handling": "Manutention",
    "Fee": "Frais",
    "Fees": "Frais",
    "Charge": "Frais",
    "Charges": "Frais",
    "Refund": "Remboursement",
    "Exchange": "Échange",
    "Return": "Retour",
    "Product": "Produit",
    "Products": "Produits",
    "Service": "Service",
    "Services": "Services",
    "Item": "Article",
    "Items": "Articles",
    "Order": "Commande",
    "Orders": "Commandes",
    "Purchase": "Achat",
    "Purchases": "Achats",
    "Sale": "Vente",
    "Sales": "Ventes",
    "Customer": "Client",
    "Customers": "Clients",
    "Client": "Client",
    "Clients": "Clients",
    "Vendor": "Fournisseur",
    "Vendors": "Fournisseurs",
    "Supplier": "Fournisseur",
    "Suppliers": "Fournisseurs",
    "Partner": "Partenaire",
    "Partners": "Partenaires",
    "Stakeholder": "Partie prenante",
    "Stakeholders": "Parties prenantes",
    "Contact Person": "Personne de contact",
    "First Name": "Prénom",
    "Last Name": "Nom de famille",
    "Full Name": "Nom complet",
    "Display Name": "Nom d'affichage",
    "Nickname": "Surnom",
    "Title": "Titre",
    "Prefix": "Préfixe",
    "Suffix": "Suffixe",
    "Gender": "Genre",
    "Male": "Homme",
    "Female": "Femme",
    "Other": "Autre",
    "Date of Birth": "Date de naissance",
    "Birth Date": "Date de naissance",
    "Age": "Âge",
    "Nationality": "Nationalité",
    "Citizenship": "Citoyenneté",
    "Marital Status": "État civil",
    "Single": "Célibataire",
    "Married": "Marié",
    "Divorced": "Divorcé",
    "Widowed": "Veuf",
    "Emergency Contact": "Contact d'urgence",
    "Relationship": "Relation",
    "Spouse": "Conjoint",
    "Parent": "Parent",
    "Child": "Enfant",
    "Sibling": "Frère/Sœur",
    "Relative": "Proche",
    "Friend": "Ami",
    "Colleague": "Collègue",
    "Supervisor": "Superviseur",
    "Subordinate": "Subordonné",
    "Peer": "Pair",
    "Department Head": "Chef de département",
    "Division": "Division",
    "Branch": "Succursale",
    "Office": "Bureau",
    "Headquarters": "Siège social",
    "Region": "Région",
    "Zone": "Zone",
    "Territory": "Territoire",
    "District": "District",
    "Area": "Zone",
    "Building": "Bâtiment",
    "Floor": "Étage",
    "Room": "Salle",
    "Desk": "Bureau",
    "Workstation": "Poste de travail",
    "Station": "Station",
    "Site": "Site",
    "Facility": "Installation",
    "Warehouse": "Entrepôt",
    "Factory": "Usine",
    "Plant": "Usine",
    "Store": "Magasin",
    "Shop": "Boutique",
    "Outlet": "Point de vente",
    "Showroom": "Salle d'exposition",
    "Laboratory": "Laboratoire",
    "Workshop": "Atelier",
    "Clinic": "Clinique",
    "Hospital": "Hôpital",
    "School": "École",
    "University": "Université",
    "College": "Collège",
    "Institute": "Institut",
    "Academy": "Académie",
    "Library": "Bibliothèque",
    "Museum": "Musée",
    "Theater": "Théâtre",
    "Stadium": "Stade",
    "Arena": "Arène",
    "Gym": "Gymnase",
    "Pool": "Piscine",
    "Court": "Tribunal",
    "Field": "Terrain",
    "Track": "Piste",
    "Course": "Cours",
    "Range": "Portée",
    "Zone": "Zone",
}


def extract_text_from_source(source_elem):
    """Extract text content from source element, handling XML tags"""
    if source_elem.text:
        text = source_elem.text.strip()
        # Remove interpolation markers and XML tags for translation lookup
        # But keep the full text for exact matching
        return text
    return ""


def translate_text(text: str) -> str:
    """Translate English text to French"""
    # Direct lookup
    if text in TRANSLATIONS:
        return TRANSLATIONS[text]

    # Strip whitespace and try again
    stripped = text.strip()
    if stripped in TRANSLATIONS:
        # Preserve original whitespace
        if text.startswith(' ') and text.endswith(' '):
            return ' ' + TRANSLATIONS[stripped] + ' '
        elif text.startswith(' '):
            return ' ' + TRANSLATIONS[stripped]
        elif text.endswith(' '):
            return TRANSLATIONS[stripped] + ' '
        return TRANSLATIONS[stripped]

    # If no translation found, return empty string (will skip adding target)
    return ""


def process_xliff_file(input_path: str, output_path: str):
    """Process XLIFF file and add French translations"""

    # Parse XML
    tree = ET.parse(input_path)
    root = tree.getroot()

    # Define namespace
    ns = {'xliff': 'urn:oasis:names:tc:xliff:document:1.2'}

    # Register namespace to preserve it in output
    ET.register_namespace('', 'urn:oasis:names:tc:xliff:document:1.2')

    # Find all trans-units
    trans_units = root.findall('.//xliff:trans-unit', ns)

    translated_count = 0
    skipped_count = 0

    for unit in trans_units:
        source = unit.find('xliff:source', ns)
        target = unit.find('xliff:target', ns)

        # Skip if no source or source is empty
        if source is None or not source.text:
            skipped_count += 1
            continue

        # Skip if source contains only XML placeholders (interpolations, etc.)
        source_text = extract_text_from_source(source)
        if not source_text or source_text.startswith('<x id='):
            skipped_count += 1
            continue

        # Skip if target already exists
        if target is not None:
            continue

        # Get translation
        translation = translate_text(source_text)

        if translation:
            # Create target element
            target = ET.Element('{urn:oasis:names:tc:xliff:document:1.2}target')
            target.text = translation

            # Insert target after source
            source_index = list(unit).index(source)
            unit.insert(source_index + 1, target)

            translated_count += 1
        else:
            skipped_count += 1

    # Write output
    tree.write(output_path, encoding='UTF-8', xml_declaration=True)

    print(f"Translation complete!")
    print(f"Translated: {translated_count} entries")
    print(f"Skipped: {skipped_count} entries (no translation available or interpolation-only)")
    print(f"Total trans-units processed: {len(trans_units)}")


if __name__ == "__main__":
    input_file = r"E:\Repositories\ShiftSchedulerAngular\src\locale\messages.fr.xlf"
    output_file = r"E:\Repositories\ShiftSchedulerAngular\src\locale\messages.fr.xlf.new"

    process_xliff_file(input_file, output_file)
